#FROM gcr.io/google-containers/debian-base-amd64:0.3.2
#FROM gcr.io/kubeflow-images-public/jupyter-web-app:v0.5.0
#FROM gcr.io/kubeflow-images-public/centraldashboard:v0.5.0
#FROM gcr.io/kubeflow-images-public/katib/katib-ui:v0.1.2-alpha-156-g4ab3dbd
#FROM gcr.io/kubeflow-images-public/katib/metrics-collector:v0.1.2-alpha-156-g4ab3dbd
#FROM gcr.io/kubeflow-images-public/katib/studyjob-controller:v0.1.2-alpha-156-g4ab3dbd
#FROM gcr.io/kubeflow-images-public/katib/suggestion-bayesianoptimization:v0.1.2-alpha-156-g4ab3dbd
#FROM gcr.io/kubeflow-images-public/katib/suggestion-grid:v0.1.2-alpha-156-g4ab3dbd
#FROM gcr.io/kubeflow-images-public/katib/suggestion-hyperband:v0.1.2-alpha-156-g4ab3dbd
#FROM gcr.io/kubeflow-images-public/katib/suggestion-random:v0.1.2-alpha-156-g4ab3dbd
#FROM gcr.io/kubeflow-images-public/katib/vizier-core:v0.1.2-alpha-156-g4ab3dbd
#FROM gcr.io/kubeflow-images-public/katib/vizier-core-rest:v0.1.2-alpha-156-g4ab3dbd
#FROM gcr.io/kubeflow-images-public/notebook-controller:v20190401-v0.4.0-rc.1-308-g33618cc9-e3b0c4
#FROM gcr.io/kubeflow-images-public/pytorch-operator:v0.5.0
#FROM gcr.io/kubeflow-images-public/tf_operator:v0.5.0
#FROM gcr.io/ml-pipeline/api-server:0.1.16
#FROM gcr.io/ml-pipeline/scheduledworkflow:0.1.16
#FROM gcr.io/ml-pipeline/persistenceagent:0.1.16
#FROM gcr.io/ml-pipeline/viewer-crd-controller:0.1.16
#FROM gcr.io/ml-pipeline/frontend:0.1.16
FROM k8s.gcr.io/volume-nfs:0.8
